#!/bin/sh

function fail {
	echo "ERROR: $1" >&2
	exit 1
}

function configure {
	ldapmodify -Y EXTERNAL -H ldapi:/// <<-_EOF
		dn: olcDatabase={1}mdb,cn=config
		replace: olcRootPW
		olcRootPW: $CONF_ROOTPW
		-
		replace: olcSuffix
		olcSuffix: $CONF_BASEDN
		-
		replace: olcRootDN
		olcRootDN: cn=admin,$CONF_BASEDN

		dn: olcDatabase={0}config,cn=config
		replace: olcRootPW
		olcRootPW: $CONF_ROOTPW

		dn: olcDatabase={1}mdb,cn=config
		changetype: modify
		delete: olcAccess
		olcAccess: {2}
		-
		add: olcAccess
		olcAccess: {2}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
		-
		add: olcAccess
		olcAccess: {3}to * by * read
		_EOF
	return $?
}

chown -R ldap:ldap /config /data || fail "Cannot change owner of supplied volumes."

if [[ ! -d '/config/cn=config' ]] ; then
	# supplied empty config volume, use defaults
	[[ -z "$CONF_ROOTPW" ]] && fail "No existing config found and CONF_ROOTPW not given."
	[[ -z "$CONF_BASEDN" ]] && fail "No existing config found and CONF_BASEDN not given."
	[[ "${CONF_ROOTPW:0:1}" == '{' ]] || CONF_ROOTPW=`slappasswd -s "$CONF_ROOTPW"`
	cp -a /etc/openldap/. /config/
	echo "Starting temporary slapd to modify dynamic config."
	/usr/sbin/slapd -F /config -u openldap -g openldap -h ldapi:// -d stats &
	dpid=$!

	CONFIGURED=0
	for i in {1..10} ; do
		sleep 1
		configure && CONFIGURED=1
		[[ $CONFIGURED -eq 1 ]] && break
	done
	[[ $CONFIGURED -ne 1 ]] && fail "Unable to configure slapd (timeout?)."

	echo "Loading LDIF files from /initdb.d"
	find /initdb.d -maxdepth 1 -iname '*.ldif' | sort | while read filename ; do
		echo "* processing $filename"
		ldapadd -Y EXTERNAL -H ldapi:/// < "$filename"
	done

	echo "Stopping temporary slapd."
	# set timeout
	function timeout {
		kill -KILL $dpid
		fail "Timeout stopping temporary slapd instance."
	}
	trap timeout ALRM
	sleep 5 && kill -ALRM $$ &
	# kill slapd
	kill $dpid
	# wait for slapd exit (or timeout)
	wait $dpid
	# clear timeout
	kill %+
	trap - ALRM
fi

echo "Starting slapd."
exec /usr/sbin/slapd -F /config -u openldap -g openldap -h 'ldapi:// ldap://' -d stats
